=head1 The CPAN

Z<cpan>

Perl 5 is a pragmatic language on its own, yet the ever-pragmatic Perl
community has extended that language and made their work available to the
world. If you have a problem to solve, chances are someone's already written--and shared--Perl code for it.

X<CPAN>

Modern Perl programming makes heavy use of the CPAN (U<http://www.cpan.org/>).
The Comprehensive Perl Archive Network is an uploading and mirroring system for
redistributable, reusable Perl code. It's one of--if not I<the>--largest
archives of libraries of code in the world. The CPAN offers libraries for
everything from database access to profiling tools to protocols for almost
every network device ever created to sound and graphics libraries and wrappers
for shared libraries on your system.

Modern Perl without the CPAN is just another language. Modern Perl with the
CPAN is amazing.

X<distribution>
X<modules>

CPAN mirrors I<distributions>, or collections of reusable Perl code. A single
distribution can contain one or more I<modules>, or self-contained libraries of
Perl code. Each distribution occupies its own CPAN namespace and provides
unique metadata.

=begin tip The CPAN is Big, Really Big

The CPAN I<adds> hundreds of registered contributors and thousands of indexed
modules in hundreds of distributions every month. Those numbers do not take
into account updates. In late November 2011, search.cpan.org reported 9359
uploaders, 101656 modules, and 23808 distributions (representing growth rates
of 11.5%, 19.4%, and 14.3% since the previous edition of this book,
respectively).

=end tip

X<search.cpan.org>

The CPAN itself is merely a mirroring service. Authors upload distributions and
the CPAN sends them to mirror sites, from which users and CPAN clients
download, configure, build, test, and install them. The system succeeds because
of this simplicity as well as the contributions of thousands of volunteers
who've built on this distribution system. In particular, community standards
have evolved to identify the attributes and characteristics of well-formed CPAN
distributions. These include:

=over 4

=item * Standards for automated CPAN installers.

=item * Standards for metadata to describe what each distribution provides
and expects.

=item * Standards for documentation and licensing.

=back

Additional CPAN services provide comprehensive automated testing and reporting
to improve the quality of packaging and correctness across platforms and Perl
versions. Every CPAN distribution has its own ticket queue on
U<http://rt.cpan.org/> for reporting bugs and working with authors. CPAN sites
also link to previous distribution versions, module ratings, documentation
annotations, and more. All of this is available from
U<http://search.cpan.org/>.

X<CPAN; C<CPAN.pm>>
X<CPAN; C<CPANPLUS>>

Modern Perl installations include two clients to connect to, search, download,
build, test, and install CPAN distributions, CPAN.pm and CPANPLUS. For the most
part, each of these clients is equivalent for basic installation. This book
recommends the use of CPAN.pm solely due to its ubiquity. With a recent version
(as of this writing, 1.9800 is the latest stable release), module installation
is reasonably easy. Start the client with:

=begin screen

    $ B<cpan>

=end screen

To install a distribution within the client:

=begin screen

    $ B<cpan>
    cpan[1]> B<install Modern::Perl>

=end screen

... or to install directly from the command line:

=begin screen

    $ B<cpan Modern::Perl>

=end screen

X<CPAN; C<CPAN.pm>>

Eric Wilhelm's tutorial on configuring
CPAN.pmN<U<http://learnperl.scratchcomputing.com/tutorials/configuration/>>
includes a great troubleshooting section.

=begin sidebar

Even though the CPAN client is a core module for the Perl 5 distribution, you
will likely need to install standard development tools such as a C<make>
utility and possibly a C compiler. Windows users, see Strawberry Perl
(U<http://strawberryperl.com/>) and Strawberry Perl Professional. Mac OS X
users must install XCode. Unix and Unix-like users often have these tools
available (though Debian and Ubuntu users should install C<build-essential>).

=end sidebar

=head2 CPAN Management Tools

If your operating system provides its own installation of Perl 5, that version
may be out of date or it may have its own dependencies on specific versions of
CPAN distributions. Serious Perl developers often construct virtual walls
between the system Perl and their development Perl installations. Several
projects help to make this possible.

C<App::cpanminus> is a relatively new CPAN client with goals of speed,
simplicity, and zero configuration. Install it with C<cpan App::cpanminus>, or:

=begin screen

    $ B<curl -LO http://xrl.us/cpanm>
    $ B<chmod +x cpanm>

=end screen

C<App::perlbrew> is a system to manage and to switch between your own
installations of multiple versions and configurations of Perl. Installation is
as easy as:

=begin screen

    $ B<curl -LO http://xrl.us/perlbrew>
    $ B<chmod +x perlbrew>
    $ B<./perlbrew install>
    $ B<perldoc App::perlbrew>

=end screen

X<CPAN; local::lib>
X<CPAN; App::local::lib::helper>

The C<local::lib> CPAN distribution allows you to install and to manage
distributions in your own user directory, rather than for the system as a
whole. This is an effective way to maintain CPAN distributions without
affecting other users. Installation is somewhat more involved than the previous
two distributions, though C<App::local::lib::helper> can simplify the process.  See
U<http://search.cpan.org/perldoc?local::lib> and
U<http://search.cpan.org/perldoc?App::local::lib::helper> for more details.

All three projects tend to assume a Unix-like environment (such
as a GNU/Linux distribution or even Mac OS X). Windows users, see the Padre
all-in-one download (U<http://padre.perlide.org/download.html>).
