=head0 Preface

Perl turns 23 years old later this year.  The language has gone from a simple
tool for system administration somewhere between shell scripting and C
programming (Perl 1) to a powerful, general purpose language steeped in a rich
heritage (Perl 5) and a consistent, coherent, rethinking of programming in
general intended to last for another 25 years (Perl 6).

Even so, most Perl 5 programs in the world take far too little advantage of the
language.  You I<can> write Perl 5 programs as if they were Perl 4 programs (or
Perl 3 or 2 or 1), but programs written to take advantage of everything amazing
the worldwide Perl 5 community has invented, polished, and discovered are
shorter, faster, more powerful, and easier to maintain than their alternatives.

I<Modern Perl> is a loose description of how experienced and effective Perl 5
programmers work.  They use language idioms.  They take advantage of the CPAN.
They're recognizably Perlish, and they show good taste and craftsmanship and a
full understanding of Perl.

You can learn this too.

=head1 Running Modern Perl

Unless otherwise mentioned, code snippets always assume the basic skeleton of a
program:

=begin programlisting

    #!/usr/bin/perl

    use Modern::Perl;

    # example code here
    ...

=end programlisting

=begin sidebar

The Modern::Perl module is available from the CPAN.  You can install it
yourself or replace it with:

=begin programlisting

    use strict;
    use warnings;
    use 5.010;

=end programlisting

=end sidebar

Other code snippets use testing functions such as C<ok()>, C<like()>, and
C<is()> (L<testing>).  That skeleton program is:

=begin programlisting

    #!/usr/bin/perl

    use Modern::Perl;
    B<use Test::More;>

    # example code here
    ...
    done_testing();

=end programlisting

The examples in this book assume you're using Perl 5.10.0 or newer; ideally at
least Perl 5.10.1.  Many examples will work on older versions of Perl 5 with
modest changes, but you will have more difficulty with anything older than
5.10.0.  This book also mentions (but does not require the use of) features
found in Perl 5.12.

You can often install a new version of Perl yourself.  Windows users, download
Strawberry Perl from U<http://www.strawberryperl.com/>.  Users of other
operating systems with Perl 5 already installed (and a C compiler and the other
development tools), start by installing the CPAN module C<App::perlbrew>N<See
U<http://search.cpan.org/perldoc?App::perlbrew> for installation
instructions.>.

C<perlbrew> allows you to install and to manage multiple versions of Perl 5.
By default, it installs them to your own home directory.  Not only can you have
multiple versions of Perl 5 installed without affecting the system Perl but you
can also install any module you like into these directories without asking your
system administrator for specific permission.

=head1 Perl 5 and Perl 6

Should you learn Perl 5 or Perl 6?  They share philosophy and syntax and
libraries and community; they fill different niches.  Learn Perl 5 if:

=over 4

=item * You have existing Perl 5 code to maintain

=item * You need to take advantage of CPAN modules

=item * Your deployment strategy requires rigorous stability

=back

Learn Perl 6 if:

=over 4

=item * You're comfortable managing frequent upgrades

=item * You can afford to experiment with new syntax and features

=item * You need new features only available in Perl 6

=item * You can contribute to its development (whether patches, bug reports,
documentation, sponsorship, or other resources)

=back

In general, Perl 5 development is conservative with regard to the core
language.  For good or for ill, change occurs slowly.  Perl 6 is more
experimental, as it considers finding the best possible design more important
than keeping old code working.  Fortunately, you can learn and use both
languages (and they interoperate to an ever-improving degree).

This book discusses Perl 5.  To learn more about Perl 6, see
U<http://perl6.org/>, try Rakudo (U<http://www.rakudo.org/>, and refer to the
book I<Using Perl 6>, also published by Onyx Neon Press.
