Z<perl_community>

=head1 Community Sites

X<perl.org>
X<websites; perl.org>

Perl's homepage at U<http://www.perl.org/> links to documentation, source code,
tutorials, mailing lists, and several important community projects. If you're
new to Perl, the Perl beginners mailing list is a friendly place to ask novice
questions and get accurate and helpful answers. See
U<http://learn.perl.org/faq/beginners.html>.

The home of Perl development is U<http://dev.perl.org/>, which links to
relevant resources for Perl's core development.

X<cpan.org>
X<websites; cpan.org>
X<MetaCPAN>
X<websites; MetaCPAN>

The CPAN's (L<cpan>) central location is U<http://www.cpan.org/>, though
experienced users spend more time on U<http://search.cpan.org/> and
U<https://metacpan.org/>. Get used to browsing here for freely available libraries.

X<blogs.perl.org>
X<websites; blogs.perl.org>

Several community sites offer news and commentary. U<http://blogs.perl.org/> is
a free blog platform open to any Perl community member.

X<Enlightened Perl Organization>
X<Planet Perl>
X<Planet Perl Iron Man>
X<websites; Planet Perl>
X<websites; Planet Perl Iron Man>

Other sites aggregate the musings of Perl hackers, including
U<http://perlsphere.net/>, U<http://planet.perl.org/>, and
U<http://ironman.enlightenedperl.org/>. The latter is part of an initiative
from the Enlightened Perl Organization (U<http://enlightenedperl.org/>) to
increase the amount and improve the quality of Perl publishing on the web.

X<Perl Buzz>
X<websites; Perl Buzz>
X<Perl Weekly>
X<websites; Perl Weekly>

Perl Buzz (U<http://perlbuzz.com/>) collects and republishes some of the most
interesting and useful Perl news on a regular basis. Perl Weekly
(U<http://perlweekly.com/>) offers a weekly take on news from the Perl world.

=head1 Development Sites

X<RT>
X<Best Practical>

Best Practical Solutions (U<http://bestpractical.com/>) maintains an
installation of their popular request tracking system, RT, for CPAN authors as
well as Perl development. Every CPAN distribution has its own RT queue on
U<http://rt.cpan.org/>. Perl itself has a ticket queue at
U<http://rt.perl.org/>.

X<Perl 5 Porters>
X<p5p>

The Perl 5 Porters (or I<p5p>) mailing list is the focal point of the
development of Perl. See
U<http://lists.cpan.org/showlist.cgi?name=perl5-porters>.

X<TPF>
X<The Perl Foundation>
X<TPF; wiki>
X<websites; TPF wiki>

The Perl Foundation (U<http://www.perlfoundation.org/>) hosts a wiki for all
things Perl. See U<http://www.perlfoundation.org/perl5>.

X<Github>
X<gitpan>
X<websites; gitpan>

Many Perl hackers use GithubN<U<http://github.com/>> to host their projects,
including including the sources of this
bookN<U<http://github.com/chromatic/modern_perl_book/>>. See especially Gitpan
N<U<http://github.com/gitpan/>>, which hosts Git repositories chronicling the
complete history of every distribution on the CPAN.

=begin tip A Local Git Mirror

X<CPAN; C<Git::CPAN::Patch>>
X<Champoux, Yanick>

GitPAN receives infrequent updates. As an alternative to hacking CPAN
distributions from GitPAN, consider using Yanick Champoux's wonderful
C<Git::CPAN::Patch> module to create local Git repositories from CPAN
distributions.

=end tip

=head1 Events

X<YAPC>

The Perl community holds countless conferences, workshops, seminars, and
meetings. In particular, the community-run YAPC--Yet Another Perl
Conference--is a successful, local, low-cost conference model held on multiple
continents. See U<http://yapc.org/>.

The Perl Foundation wiki lists other events at
U<http://www.perlfoundation.org/perl5/index.cgi?perl_events>.

X<Perl Mongers>

Hundreds of local Perl Mongers groups get together frequently for technical
talks and social interaction. See U<http://www.pm.org/>.

=head1 IRC

X<IRC>
X<IRC; #moose>
X<IRC; #catalyst>
X<IRC; #perl-help>
X<IRC; #perl>

When Perl mongers can't meet in person, many collaborate and chat online
through the textual chat system known as IRC. The main server for Perl
community is C<irc://irc.perl.org/>. Be aware that the channel I<#perl> is a
general purpose channel for discussing whatever its participants want to
discuss. Direct questions to I<#perl-help> instead. Many of the most popular
and useful Perl projects have their own IRC channels, such as I<#moose> and
I<#catalyst>; you can find mention of these channels in project documentation.
